### ISSUE TITLE
Please add build instructions

### ISSUE THREAD

**Issue by unixorn** [reujab/bronze#3]
`go install github.com/reujab/bronze` fails with

```
go install github.com/reujab/bronze
# pkg-config --cflags libgit2
Package libgit2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgit2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libgit2' found
pkg-config: exit status 1
```

**Comment by reujab** [comment]
Right, I forgot to add the compilation dependency of libgit2. It was on my to-do list, but I never got around to adding it to the readme. I will do that later today. Thank you for reminding me.
