### ISSUE TITLE
can not compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by thugcee** [reujab/bronze#5]
go version: 1.6.2 linux/amd64

The error I get is:
```
$ go get github.com/reujab/bronze
# cd /opt/go/src/gopkg.in/libgit2/git2go.v26; git submodule update --init --recursive
Submodule 'vendor/libgit2' (https://github.com/libgit2/libgit2) registered for path 'vendor/libgit2'
Cloning into 'vendor/libgit2'...                         
Submodule path 'vendor/libgit2': checked out '15e119375018fba121cf58e02a9f17fe22df0df8'
fatal: no submodule mapping found in .gitmodules for path 'tests/resources/rebase-submodule/my-submodule'
Failed to recurse into submodule path 'vendor/libgit2' 
package gopkg.in/libgit2/git2go.v26: exit status 128
package plugin: unrecognized import path "plugin" (import path does not begin with hostname)

```

**Comment by reujab** [comment]
That seems to be an issue with [git2go](https://github.com/libgit2/git2go). If you run the command again, it should not give the error and product a valid binary.

Does running `go get github.com/reujab/bronze` again work? If so, I will update the readme.

**Comment by thugcee** [comment]
Unfortunately it doesn't . After clean up and starting everything from the beginning, the second run gives:
```
$ go get github.com/reujab/bronze
package plugin: unrecognized import path "plugin" (import path does not begin with hostname)
```

Maybe the source of the problem is the version of libgit2-dev? Ubuntu 16.04 has libgit2-dev v0.24.

On one machine I've managed to install libgit2-dev v0.26 with all its dependencies so I could use binary file of _bronze_ and it works great. thx :)

**Comment by reujab** [comment]
If the error is with importing the `plugin` package, it must be an error with bronze, since only bronze imports that package. Or maybe it's because your Ubuntu machine is using an older version of Go that doesn't support plugins (<1.8)?

What's the output of `go version` on the Ubuntu machine?

**Comment by thugcee** [comment]
That's it
```
$ go version
go version go1.6.2 linux/amd64
```
Thanks :)
