### ISSUE TITLE
weird prompt issue?

### ISSUE THREAD

**Issue by SolarAquarion** [reujab/bronze#9]
omf theme bullet-train-fish-theme                        Fri 08 Jun 2018 10:05:29 AM EDT
set --erase: Expected 1 args, got 2
~/.local/share/omf/lib/autoload.fish (line 85): 
    and set -e fish_function_path[$function_indexes]
        ^
in function “__autoload_erase”
	called on line 6 of file ~/.local/share/omf/lib/autoload.fish
	with parameter list “/home/solaraquarion/.config/omf/themes/bobthefish /home/solaraquarion/.local/share/omf/themes/bobthefish /home/solaraquarion/.config/omf/themes/bobthefish/functions /home/solaraquarion/.local/share/omf/themes/bobthefish/functions”

in function “autoload”
	called on line 25 of file ~/.local/share/omf/pkg/omf/functions/themes/omf.theme.set.fish
	with parameter list “-e /home/solaraquarion/.config/omf/themes/bobthefish /home/solaraquarion/.local/share/omf/themes/bobthefish /home/solaraquarion/.config/omf/themes/bobthefish/functions /home/solaraquarion/.local/share/omf/themes/bobthefish/functions”

in function “omf.theme.set”
	called on line 18 of file ~/.local/share/omf/pkg/omf/functions/cli/omf.cli.theme.fish
	with parameter list “bullet-train-fish-theme”

in function “omf.cli.theme”
	called on line 3 of file -
	with parameter list “bullet-train-fish-theme”

in function “__omf_last_command”
	called on line 51 of file ~/.local/share/omf/pkg/omf/functions/omf.fish

in function “omf”
	called on standard input
	with parameter list “theme bullet-train-fish-theme”

       set

   Synopsis
       set [SCOPE_OPTIONS]
       set [OPTIONS] VARIABLE_NAME VALUES...
       set [OPTIONS] VARIABLE_NAME[INDICES]... VALUES...
       set ( -q | --query ) [SCOPE_OPTIONS] VARIABLE_NAMES...
       set ( -e | --erase ) [SCOPE_OPTIONS] VARIABLE_NAME
       set ( -e | --erase ) [SCOPE_OPTIONS] VARIABLE_NAME[INDICES]...
       set ( -S | --show ) [SCOPE_OPTIONS] [VARIABLE_NAME]...

set: Type “help set” for related documentation

**Comment by reujab** [comment]
What is your fish configuration?

**Comment by SolarAquarion** [comment]
I posted this in the wrong issue tracker lol
